// <auto-generated />
using System;
using DtuFoodAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DtuFoodAPI.Database.Migrations
{
    [DbContext(typeof(DtuFoodDbContext))]
    [Migration("20251105225802_AddProductCategories")]
    partial class AddProductCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DtuFoodAPI.Models.Availability", b =>
                {
                    b.Property<Guid>("TruckId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("OpeningTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("TruckId", "DayOfWeek");

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("DtuFoodAPI.Models.FoodTruck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("GpsLatitude")
                        .HasColumnType("real");

                    b.Property<float>("GpsLongitude")
                        .HasColumnType("real");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("FoodTrucks");
                });

            modelBuilder.Entity("DtuFoodAPI.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Blob")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("DtuFoodAPI.Models.Product", b =>
                {
                    b.Property<Guid>("TruckId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("case_insensitive");

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("TruckId", "Name");

                    b.HasIndex("ImageId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DtuFoodAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FoodTruckUser", b =>
                {
                    b.Property<Guid>("FoodTrucksId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManagersId")
                        .HasColumnType("uuid");

                    b.HasKey("FoodTrucksId", "ManagersId");

                    b.HasIndex("ManagersId");

                    b.ToTable("FoodTruckUser");
                });

            modelBuilder.Entity("DtuFoodAPI.Models.Availability", b =>
                {
                    b.HasOne("DtuFoodAPI.Models.FoodTruck", "Truck")
                        .WithMany("Availability")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("DtuFoodAPI.Models.FoodTruck", b =>
                {
                    b.HasOne("DtuFoodAPI.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("DtuFoodAPI.Models.Product", b =>
                {
                    b.HasOne("DtuFoodAPI.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("DtuFoodAPI.Models.FoodTruck", "FoodTruck")
                        .WithMany("Products")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodTruck");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("FoodTruckUser", b =>
                {
                    b.HasOne("DtuFoodAPI.Models.FoodTruck", null)
                        .WithMany()
                        .HasForeignKey("FoodTrucksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DtuFoodAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ManagersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DtuFoodAPI.Models.FoodTruck", b =>
                {
                    b.Navigation("Availability");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
