# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Some randomly generated signing keys, not used in production
env:
  Authentication:Schemes:Refresh:SigningKeys:0:Value: '+t96aFoRNeWOCcbn035jDflLSbWVfVn06xXPpbApJtN2ZqTPdkbTiDu57PQ3GFcrQbfj2oQ5jteGYIGVpa/0xmeumDvrzM1qvyt1P0j2NU69jg1WGR6gb0p5RARSsJVTg17QJ61Z9bIzA43CbA9gXyHbk0kYEYBJimAlFt1gaKBEhD+9RTUDPDoIgTDUGRpiv0OzY+ISyB4spIVMGGMyvU5kOJTVGXbf/PaOod0lNBHKzxFLNR8FIfnz9Xon7H4Gpdvuq5hdAMbdH748uJNLKKoCU40+BbOyfTuLyUDJ3g/uKFcPCj9ZhvRtqiRnHmdhJa0KwTwZA7oG8wO7UXmelQ=='
  Authentication:Schemes:Access:SigningKeys:0:Value: 'ZbE2F1j9kCpp/m7oK/4k26zjSyI14NfLkuF3QBsFk5xvx0M7J3jdpRpRI5AEecCVrpWC8e6/fRzYRRY0jleXJocz2LqniXdfc5QykK8UAoXFhIAaS04xKsApV+N8CJF3gWfl5U9t7+ozarhg+P8pvy2qbRr3Zs7/gh+02ZbAwR2Yyh/D4acNwMipusg6WCeRMKAlKe2cwq7EVymXDWz4h5jxHp4u2D/82lfaJNTiP7tmm8HlEHk2yxy0+m17wRhXRoATNUTJqioKEOvDQYTiWTdeCMd69KHclccWqq3B5eUsonE8/1YYQcQZfrz9D1g4CNMRnIxZi2cJxMPP7pfyAA=='

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
